[advisories]
vulnerability = "deny"
unmaintained = "deny"
notice = "deny"
unsound = "deny"

[licenses]
unlicensed = "deny"
confidence-threshold = 0.9
allow-osi-fsf-free = "neither"
allow = [
    "MIT",
    "Apache-2.0",
    "BSL-1.0",
    "GPL-3.0",
]
default = "deny"

[bans]
multiple-versions = "deny"
wildcards = "warn"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = ["https://github.com/emberian/evdev"]
